# Generated by Django 2.1 on 2018-11-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myControl', '0002_auto_20181021_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
